-- used_books (돌고 돌아 책장 중고 도서) 테이블 생성
CREATE TABLE IF NOT EXISTS public.used_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_name TEXT NOT NULL,
    title TEXT NOT NULL,
    price INTEGER DEFAULT 0,
    discount_price INTEGER DEFAULT 0,
    discount_rate INTEGER DEFAULT 0,
    quality TEXT NOT NULL CHECK (quality IN ('최상 (A급)', '우수 (B급)', '보통 (C급)')),
    cover_image TEXT,
    story TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS 비활성화 (개발의 신속성 및 프로토타입 용도)
ALTER TABLE public.used_books DISABLE ROW LEVEL SECURITY;

-- 기존 Mock 데이터 삽입
INSERT INTO public.used_books (id, donor_name, title, price, discount_price, discount_rate, quality, cover_image, story)
VALUES
(1, '@autumn_reader', '골목길 산책자 (초판)', 16000, 11200, 30, '최상 (A급)', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400&fm=webp', '2년 전 파리 여행에서 함께했던 책입니다. 귀퉁이가 조금 닳았지만 여전히 좋은 문장들이 가득해요.'),
(2, '@book_lover_99', '당신을 닮은 고요한 정원', 14000, 8400, 40, '우수 (B급)', 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400&fm=webp', '우울할 때마다 꺼내 읽었던 책. 34페이지에 제가 남긴 짧은 메모가 누군가에게 위로가 되길 바랍니다.'),
(3, '@coffee_n_books', '마음이 흐르는 대로', 15000, 9000, 40, '우수 (B급)', 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&fm=webp', '커피 얼룩이 아주 살짝 묻어있어요. 그래서 더 정감이 가는 저만의 애착 책이었습니다. 이제 보내주려구요.'),
(4, '@daily_record', '나의 작은 별에게', 13000, 9100, 30, '최상 (A급)', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&fm=webp', '아이에게 읽어주던 동화책입니다. 겉표지는 바랬지만 속지는 아주 깨끗해요.'),
(5, '@evening_sky', '시가 되는 일상', 12000, 7200, 40, '우수 (B급)', 'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?auto=format&fit=crop&q=80&w=400&fm=webp', '좋아하는 시구절에 노란색 형광펜으로 밑줄을 쳐두었습니다. 그 문장들이 새 주인을 기쁘게 했으면 해요.'),
(6, '@film_maker', '필름과 문장', 18000, 9000, 50, '보통 (C급)', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=400&fm=webp', '절판된 희귀본입니다. 상태는 보통이지만 내용의 가치는 충분합니다.'),
(7, '@green_day', '여름의 맛', 14000, 8400, 40, '우수 (B급)', 'https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&fm=webp', '지난 여름 휴가때 가방에 넣어다니며 읽어 약간 휘었지만, 여름의 향기가 배어있습니다.'),
(8, '@hello_stranger', '모르는 사람에게 쓰는 편지', 15000, 10500, 30, '최상 (A급)', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&fm=webp', '책 사이에 제가 직접 압화한 네잎클로버 코팅지가 들어있습니다. 행운을 빕니다!'),
(9, '@into_the_unknown', '어느 날 문득', 13500, 6750, 50, '보통 (C급)', 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&fm=webp', '표지가 조금 찢어졌지만 테이프로 예쁘게 붙여두었습니다. 사연 있는 책을 좋아하는 분께.'),
(10, '@just_read', '단순하게 사는 법', 16000, 11200, 30, '최상 (A급)', 'https://images.unsplash.com/photo-1618666012174-83b441c0bc76?auto=format&fit=crop&q=80&w=400&fm=webp', '미니멀라이프를 실천하며 책장 정리를 위해 내놓습니다. 거의 새 책이에요.'),
(11, '@keep_going', '오늘도 수고했어', 14500, 8700, 40, '우수 (B급)', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&fm=webp', '힘들 때마다 저를 다독여준 책입니다. 다음 분에게도 힘이 되기를.'),
(12, '@life_is_journey', '지도 없는 여행', 16500, 9900, 40, '우수 (B급)', 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&q=80&w=400&fm=webp', '오래된 책 특유의 종이 냄새가 매력적입니다. 여행지에서 읽기 좋아요.')
ON CONFLICT (id) DO UPDATE SET
  donor_name = EXCLUDED.donor_name,
  title = EXCLUDED.title,
  price = EXCLUDED.price,
  discount_price = EXCLUDED.discount_price,
  discount_rate = EXCLUDED.discount_rate,
  quality = EXCLUDED.quality,
  cover_image = EXCLUDED.cover_image,
  story = EXCLUDED.story;
