-- 1. books 테이블에 상세 정보 컬럼 추가
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS table_of_contents TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS author_intro TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS pages TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS publish_date TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS isbn TEXT;

-- 2. book_reviews (도서 리뷰) 테이블 신규 생성
CREATE TABLE IF NOT EXISTS public.book_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. 기존 시드 도서들에 상세 설명 정보 업데이트
-- (ID 1: 참을 수 없는 존재의 가벼움)
UPDATE public.books
SET 
    description = '<div class="space-y-6 font-serif text-[15px] leading-[1.8] text-gray-700"><p>밀란 쿤데라의 대표작으로, 역사적 개인의 운명과 생의 가벼움 및 무거움 사이의 영원한 갈등을 다룬 걸작 소설입니다.</p><p>체코 프라하의 봄을 배경으로 네 남녀의 사랑과 삶을 철학적인 사유와 함께 그려냈습니다.</p></div>',
    table_of_contents = '<ul class="space-y-4 font-sans text-sm text-gray-700"><li class="flex gap-4"><span class="font-serif font-bold text-gray-400 w-6">1부</span><span>가벼움과 무거움</span></li><li class="flex gap-4"><span class="font-serif font-bold text-gray-400 w-6">2부</span><span>영혼과 육체</span></li><li class="flex gap-4"><span class="font-serif font-bold text-gray-400 w-6">3부</span><span>이해받지 못한 말들</span></li></ul>',
    author_intro = '<p class="font-sans text-sm text-gray-600 leading-relaxed">밀란 쿤데라는 체코 브르노에서 태어나 1975년 프랑스로 망명하였다. 소설뿐만 아니라 시, 희곡, 에세이 등 다양한 문학 장르에서 독보적인 세계를 구축하였으며 현대 문학의 거장으로 평가받는다.</p>',
    pages = '520쪽 / 480g',
    publish_date = '2018년 06월 20일',
    isbn = '9788937462344'
WHERE id = 1;

-- (ID 2: 어느 날, 내 마음에 자리 잡은 것들)
UPDATE public.books
SET 
    description = '<div class="space-y-6 font-serif text-[15px] leading-[1.8] text-gray-700"><p>피천득 작가의 잔잔하고 다정한 문체로 쓰인 인생 수필집입니다.</p><p>소소한 일상에서 길어 올린 아름다운 통찰과 따스함이 가득 담긴 감성 에세이입니다.</p></div>',
    table_of_contents = '<ul class="space-y-4 font-sans text-sm text-gray-700"><li class="flex gap-4"><span class="font-serif font-bold text-gray-400 w-6">1장</span><span>은전 한 닢</span></li><li class="flex gap-4"><span class="font-serif font-bold text-gray-400 w-6">2장</span><span>인연 (因緣)</span></li><li class="flex gap-4"><span class="font-serif font-bold text-gray-400 w-6">3장</span><span>플루트 연주자</span></li></ul>',
    author_intro = '<p class="font-sans text-sm text-gray-600 leading-relaxed">피천득은 한국 수필 문학의 거목으로, 한국 현대 문학의 기틀을 마련했다. 그의 수필은 소박하고 순수한 감성을 정제된 문장으로 서술하여 오랜 세월 독자들에게 잔잔한 울림을 안겨주고 있다.</p>',
    pages = '248쪽 / 300g',
    publish_date = '2015년 11월 05일',
    isbn = '9788937400122'
WHERE id = 2;

-- 4. 초기 예시 리뷰 데이터 삽입
INSERT INTO public.book_reviews (book_id, user_name, rating, review_text)
VALUES
(1, '책좋아하는독자', 5, '생과 사, 무거움과 가벼움의 대비가 아주 강렬했습니다. 인생의 나침반이 되어준 책입니다.'),
(1, '라떼파파', 4, '내용은 무겁지만 읽을 가치가 아주 큽니다. 번역도 매끄럽고 좋습니다.'),
(2, '봄날의곰', 5, '피천득 작가님의 따뜻한 글이 마음의 평화를 가져다 주네요. 적극 추천합니다.')
ON CONFLICT (id) DO NOTHING;
