-- 1. profiles (사용자 추가 정보) 테이블 생성
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    name TEXT,
    role TEXT DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. events (소모임/이벤트) 테이블 생성
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date_info TEXT NOT NULL,
    description TEXT,
    max_seats INTEGER DEFAULT 10,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. event_applications (소모임/이벤트 신청 내역) 테이블 생성
CREATE TABLE IF NOT EXISTS public.event_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    contact TEXT NOT NULL,
    seats INTEGER DEFAULT 1,
    notes TEXT,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    admin_comment TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. books (도서 정보) 테이블 생성
CREATE TABLE IF NOT EXISTS public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    publisher TEXT,
    price INTEGER DEFAULT 0,
    cover_image TEXT,
    stock INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. book_orders (도서 모의 결제 주문 내역) 테이블 생성
CREATE TABLE IF NOT EXISTS public.book_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1,
    total_price INTEGER DEFAULT 0,
    payment_method TEXT DEFAULT '카드',
    status TEXT DEFAULT 'PAYMENT_PENDING' CHECK (status IN ('PAYMENT_PENDING', 'COMPLETED', 'CANCELLED')),
    shipping_address TEXT,
    buyer_name TEXT,
    buyer_phone TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Row Level Security (RLS) 비활성화 (프로토타입 개발의 신속성을 위해 비활성화)
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.books DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_orders DISABLE ROW LEVEL SECURITY;

-- 7. auth.users 테이블에 신규 가입 발생 시 public.profiles에 자동 복사하는 트리거 설정
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, role)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'role', 'USER')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 기존 트리거가 존재하면 드롭하고 새로 생성
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 8. 초기 Mock 데이터 삽입 (기존 하드코딩 데이터 연동용)

-- 8-1. 소모임/이벤트 초기 데이터 삽입
INSERT INTO public.events (id, title, date_info, description, max_seats, image_url)
VALUES
(1, '여름밤의 필사 모임', '2026.07.20 ~ 2026.08.10 (매주 목 19:30)', '매미 소리가 잦아드는 늦은 저녁, 시원한 차 한 잔과 함께 온전히 문장에 집중하는 시간을 가집니다. 좋아하는 책의 구절을 손으로 꾹꾹 눌러 쓰며 하루의 피로를 씻어보세요. 서로의 필사 노트를 공유하며 잔잔한 대화도 나눕니다.', 15, 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=800&auto=format&fit=crop'),
(2, '나만을 위한 심야 책방', '매주 금요일 22:00 ~ 익일 02:00', '모두가 잠든 시간, 불이 꺼지지 않는 책방에서 온전한 고독을 즐겨보세요. 백색소음과 은은한 조명 아래서 책을 읽거나 밀린 다이어리를 씁니다. 입장 시 따뜻한 드립 커피 1잔이 제공됩니다.', 10, 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=800&auto=format&fit=crop'),
(3, '이달의 작가 북토크', '2026.08.15 (토) 15:00 ~ 17:00', '베스트셀러 <어느 날, 내 마음에 자리 잡은 것들>의 김하나 작가님을 모시고 이야기를 나눕니다. 책이 쓰이게 된 배경, 집필 과정의 비하인드 스토리, 그리고 독자들과의 Q&A 시간이 준비되어 있습니다. 종료 후 사인회가 이어집니다.', 30, 'https://images.unsplash.com/photo-1544928147-79a2dbc1f389?q=80&w=800&auto=format&fit=crop'),
(4, '독립출판 워크숍 1기', '2026.09.01 ~ 2026.10.20 (총 8주 과정)', '나만의 글을 한 권의 책으로 엮어내는 전 과정을 함께합니다. 기획부터 원고 작성, 인디자인 기초, 가제본 제작, 그리고 독립서점 입고 방법까지. 책방지기와 외부 전문가가 밀착 코칭합니다. 나만의 이야기를 세상에 꺼내어보세요.', 8, 'https://images.unsplash.com/photo-1463320726281-696a485928c7?q=80&w=800&auto=format&fit=crop')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  date_info = EXCLUDED.date_info,
  description = EXCLUDED.description,
  max_seats = EXCLUDED.max_seats,
  image_url = EXCLUDED.image_url;

-- 8-2. 도서 초기 데이터 삽입
INSERT INTO public.books (id, title, author, publisher, price, cover_image, stock)
VALUES
(1, '참을 수 없는 존재의 가벼움', '밀란 쿤데라', '민음사', 16000, 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=600&auto=format&fit=crop', 20),
(2, '어느 날, 내 마음에 자리 잡은 것들', '피천득', '민음사', 15800, 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=600&auto=format&fit=crop', 15),
(3, '고요한 우연', '기욤 뮈소', '밝은세상', 16800, 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&auto=format&fit=crop', 12),
(4, '다정한 매일매일', '김용택', '작가정신', 14500, 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?q=80&w=600&auto=format&fit=crop', 8),
(5, '우리가 빛의 속도로 갈 수 없다면', '김초엽', '허블', 14000, 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=600&auto=format&fit=crop', 25),
(6, '아주 오랜만에 행복하다는 느낌', '박완서', '작가정신', 15000, 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?q=80&w=600&auto=format&fit=crop', 10),
(7, '모든 것은 기본에서 시작한다', '손웅정', '수오서재', 16000, 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?q=80&w=600&auto=format&fit=crop', 5),
(8, '숲속의 자본주의자', '박혜윤', '다산초당', 15000, 'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?q=80&w=600&auto=format&fit=crop', 7)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  publisher = EXCLUDED.publisher,
  price = EXCLUDED.price,
  cover_image = EXCLUDED.cover_image,
  stock = EXCLUDED.stock;

-- 9. curations (1회성 심층 북 큐레이션 신청) 테이블 생성
CREATE TABLE IF NOT EXISTS public.curations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    contact TEXT NOT NULL,
    address TEXT,
    age_info TEXT,
    preference TEXT,
    environment TEXT,
    referral TEXT,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 9-1. 초기 큐레이션 신청 내역 Mock 데이터 삽입
INSERT INTO public.curations (id, name, contact, address, age_info, preference, environment, referral, status)
VALUES
(1022, '김도윤', '010-5555-4444', '부산 해운대구', '40대 이상', '지친 하루 끝, 위로가 되는 책', '햇살 드는 베란다', '검색엔진', 'PENDING'),
(1023, '이서연', '010-9876-5432', '경기 성남시', '30대', '퇴근 후 30분씩 가볍게 읽을 수 있는 위로가 되는 에세이', '조용한 심야 카페', '지인 추천', 'APPROVED'),
(1024, '박지우', '010-1234-5678', '서울 마포구', '20대', '최근에 번아웃이 왔어요. 아무 생각 없이 푹 빠져들 수 있는 소설을 원해요.', '비 오는 날 따뜻한 방안', '인스타그램', 'PENDING')
ON CONFLICT (id) DO NOTHING;

