'use client'

import { useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowDown, ArrowRight, BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight, Camera, Menu, X } from 'lucide-react'
import { books, faqs, keywordGroups, photos, reviews, type Book } from '@/lib/life-data'

const warmImage = (src: string) => `${src}&auto=format&fit=crop&w=900&q=85`

export default function Page() {
  const [intro, setIntro] = useState(true)
  const [selected, setSelected] = useState<string[]>([])
  const [photo, setPhoto] = useState<number | null>(null)
  const [book, setBook] = useState<Book | null>(null)
  const [loading, setLoading] = useState(false)
  const [faq, setFaq] = useState<number | null>(0)
  const [review, setReview] = useState(0)
  const [success, setSuccess] = useState(false)
  const [form, setForm] = useState({ name: '', age: '', city: '', phone: '', gender: '', agree: false })

  const recommendation = useMemo(() => {
    if (selected.some(x => ['#압박감', '#무기력과번아웃'].includes(x)) && selected.some(x => ['#가벼운해방감', '#여유로운숨고르기'].includes(x))) return books[0]
    if (selected.some(x => ['#의기소침', '#열등감', '#답답한정체기'].includes(x)) && selected.some(x => ['#따뜻한자기수용', '#용기있는도전'].includes(x))) return books[1]
    if (selected.some(x => ['#혼란스러움', '#공허함'].includes(x)) && selected.some(x => ['#흔들리지않는단단함', '#주체적인확신'].includes(x))) return books[2]
    return books[3]
  }, [selected])
  const toggle = (word: string) => setSelected(v => v.includes(word) ? v.filter(x => x !== word) : [...v, word])
  const findBook = () => { setLoading(true); setBook(null); setTimeout(() => { setBook(recommendation); setLoading(false) }, 1500) }
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (form.name && form.age && form.city && form.phone && form.gender && form.agree) setSuccess(true) }
  const scrollForm = () => document.getElementById('apply')?.scrollIntoView({ behavior: 'smooth' })

  return <>
    <AnimatePresence>{intro && <motion.div className="intro" initial={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .8 }}><button onClick={() => setIntro(false)}>Skip intro</button><motion.div className="intro-copy" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .4 }}><span className="eyebrow">a small book for your life</span><h2>당신의 마음에는<br />어떤 책이 머물고 있나요?</h2><BookOpen size={42} strokeWidth={1} /></motion.div></motion.div>}</AnimatePresence>
    <header><a className="logo" href="#top">마음책방 <span>ㅣ</span> YOUR LIFE BOOK</a><nav><a href="#find">마음 찾기</a><a href="#reviews">후기</a><a href="#faq">자주 묻는 질문</a><button className="nav-button" onClick={scrollForm}>신청하기 <ArrowRight size={16} /></button></nav><button className="mobile-menu" aria-label="메뉴"><Menu /></button></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><span className="eyebrow">A book chosen just for you</span><h1>지나온 마음과<br /><em>다가올 나</em>를 위한<br />인생책 한 권</h1><p>당신의 오늘을 천천히 들여다보고,<br />지금 가장 필요한 문장을 골라 보내드려요.</p><a className="text-link" href="#find">내 마음 들여다보기 <ArrowDown size={17} /></a></div><div className="hero-art"><div className="sun"></div><div className="hero-note">“책은 때때로<br />나보다 나를<br />더 잘 알아본다”</div><div className="book-stack"><div className="book-spine one"></div><div className="book-spine two"></div><div className="book-spine three"></div></div></div></section>
      <section className="memory"><div className="section-heading"><span className="eyebrow">little fragments</span><h2>당신의 하루에,<br /><em>책 같은 순간</em>이 있나요?</h2><p>사진을 눌러 그날의 마음을 잠깐 꺼내보세요.</p></div><div className="polaroids">{photos.map(([src, caption], i) => <motion.button key={src} className={`polaroid p${i}`} onClick={() => setPhoto(i)} whileHover={{ y: -8, rotate: 0 }}><img src={warmImage(src)} alt={caption} /><span>{caption}</span></motion.button>)}</div></section>
      <section className="find" id="find"><div className="section-heading centered"><span className="eyebrow">find your life book</span><h2>세 가지 시간 속에서<br /><em>나의 마음</em>을 골라주세요</h2><p>정답은 없어요. 지금 떠오르는 단어를 편하게 선택해보세요.</p></div><div className="keyword-groups">{keywordGroups.map(group => <div className="keyword-group" key={group.label}><div><span className="group-label">{group.label}</span><span className="group-question">{group.question}</span></div><div className="chips">{group.words.map(word => <button className={selected.includes(word) ? 'chip selected' : 'chip'} key={word} onClick={() => toggle(word)}>{selected.includes(word) && <Check size={13} />}{word}</button>)}</div></div>)}</div><div className="result-action"><span>{selected.length ? `${selected.length}개의 마음을 골랐어요` : '마음에 닿는 단어를 골라주세요'}</span><button className="primary-button" disabled={!selected.length || loading} onClick={findBook}>{loading ? '마음을 읽는 중...' : '결과 확인하기'} <ArrowRight size={17} /></button></div>{loading && <div className="loading"><BookOpen className="breathe" size={34} /><p>당신에게 맞는 문장을 찾고 있어요</p></div>}{book && !loading && <motion.div className="result-card" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}><img src={book.cover} alt="추천 인생책 표지" /><div><span className="eyebrow">your life book</span><h3>{book.title}</h3><p className="author">{book.author}</p><p className="tagline">“{book.tagline}”</p><p>{book.reason}</p><button className="primary-button" onClick={scrollForm}>나의 인생책 받기 <ArrowRight size={17} /></button></div></motion.div>}</section>
      <section className="apply" id="apply"><div className="section-heading"><span className="eyebrow">a warm delivery</span><h2>당신의 책을<br /><em>준비할게요</em></h2><p>선택한 마음을 담아, 한 권의 책을 정성껏 보내드립니다.</p></div><form onSubmit={submit} className="form-card"><div className="selected-summary"><span>선택한 마음</span><div>{selected.length ? selected.map(x => <b key={x}>{x}</b>) : <small>아직 선택한 마음이 없어요</small>}</div></div><div className="form-grid"><label>이름<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="이름을 알려주세요" /></label><label>나이<input type="number" value={form.age} onChange={e => setForm({ ...form, age: e.target.value })} placeholder="나이" /></label><label>거주지<input value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} placeholder="도시 또는 지역" /></label><label>연락처<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="010-0000-0000" /></label></div><fieldset><legend>성별</legend><div className="gender">{['여성', '남성', '선택하지 않음'].map(g => <label key={g}><input type="radio" name="gender" value={g} checked={form.gender === g} onChange={e => setForm({ ...form, gender: e.target.value })} /><span>{g}</span></label>)}</div></fieldset><label className="agree"><input type="checkbox" checked={form.agree} onChange={e => setForm({ ...form, agree: e.target.checked })} /> 개인정보 수집 및 이용에 동의합니다 <a href="#privacy">내용 보기</a></label><button className="primary-button wide" type="submit">신청하기 <ArrowRight size={17} /></button></form></section>
      <section className="reviews" id="reviews"><div className="section-heading centered"><span className="eyebrow">from our readers</span><h2>책이 도착한 뒤,<br /><em>��음에 생긴 변화</em></h2></div><div className="review-window"><motion.div className="review-track" animate={{ x: `-${review * 100}%` }} transition={{ type: 'spring', stiffness: 250, damping: 28 }}>{reviews.map(item => <article className="review" key={item.name}><div className="avatar">{item.name[0]}</div><p className="quote">“{item.quote}”</p><div className="review-tags">{item.tags.map(t => <span key={t}>{t}</span>)}</div><div className="review-by">{item.name} <small>{item.role}</small><b>★★★★★</b></div></article>)}</motion.div></div><div className="carousel-controls"><button onClick={() => setReview(Math.max(0, review - 1))} aria-label="이전 후기"><ChevronLeft /></button><span>0{review + 1} / 0{reviews.length}</span><button onClick={() => setReview(Math.min(reviews.length - 1, review + 1))} aria-label="다음 후기"><ChevronRight /></button></div></section>
      <section className="faq" id="faq"><div className="section-heading"><span className="eyebrow">questions & answers</span><h2>궁금한 마음도<br /><em>편하게 물어보세요</em></h2></div><div className="faq-list">{faqs.map(([q, a], i) => <div className="faq-item" key={q}><button onClick={() => setFaq(faq === i ? null : i)}><span>{q}</span><ChevronDown className={faq === i ? 'rotate' : ''} /></button><AnimatePresence>{faq === i && <motion.p initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}>{a}</motion.p>}</AnimatePresence></div>)}</div></section>
      <section className="community"><div><span className="eyebrow">stay in touch</span><h2>마음책방의<br /><em>새로운 소식</em></h2></div><div className="community-links"><a href="https://instagram.com" target="_blank"><Camera /> <span>인스타그램<br /><small>@maeum.books</small></span><ArrowUpRight /></a><a href="https://smartstore.naver.com" target="_blank"><BookOpen /> <span>네이버 스마트스토어<br /><small>책과 마음을 만나는 곳</small></span><ArrowUpRight /></a></div></section>
    </main><footer><span className="logo">마음책방</span><span>당신의 삶에 다정한 문장을 보냅니다.</span><small>© 2024 마음책방. All rights reserved.</small></footer>
    <AnimatePresence>{photo !== null && <div className="modal-backdrop" onClick={() => setPhoto(null)}><motion.div className="photo-modal" onClick={e => e.stopPropagation()} initial={{ scale: .9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><button className="close" onClick={() => setPhoto(null)} aria-label="닫기"><X /></button><img src={warmImage(photos[photo][0])} alt={photos[photo][1]} /><p>{photos[photo][1]}</p></motion.div></div>}</AnimatePresence>
    <AnimatePresence>{success && <div className="modal-backdrop"><motion.div className="success-modal" initial={{ scale: .9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><span className="success-mark"><Check /></span><span className="eyebrow">thank you</span><h2>당신의 책을<br /><em>준비하고 있을게요</em></h2><p>{form.name}님의 마음을 잘 담아 보내드릴게요.<br />곧 연락드리겠습니다.</p><button className="primary-button" onClick={() => setSuccess(false)}>확인했어요</button></motion.div></div>}</AnimatePresence>
  </>
}

function ArrowUpRight() { return <ArrowRight size={18} /> }
